pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 200
    entity_recognition: true
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: RegexEntityExtractor
    case_sensitive: false
    use_word_boundaries: true

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
